version: "3.9"

services:
  # Mongodb servies
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017

  # api services
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      MONGODB_URI: mongodb://db_container:27017
      DB_NAME: my_db
    depends_on:
      - mongo_db
